### ISSUE TITLE
HoloBot with other languages

### ISSUE THREAD

**Issue by danieldangler** [ActiveNick/HoloBot#17]
I was wondering if it is possible to change the input language of the bot.

I want to change the voice to german

Hope you can help me :-)

**Comment by ActiveNick** [comment]
Yes. Note that I'm still working on finalizing the new version for Unity 2018.4+ and MRTK v2.x, so the latest code you should use is in the **Dev-2018.4-MRTKv2** branch. You can change the input language for the cloud-based Speech Recognizer here:
https://github.com/ActiveNick/HoloBot/blob/2ef7bd125ac4e969aef6afb5eb999eae548361e1/Assets/Scripts/SpeechRecognition.cs#L51
