### ISSUE TITLE
"SharingClient.dll"  not found

### ISSUE THREAD

**Issue by eswarborra** [ActiveNick/HoloBot#2]
Dose it works on Emulator..!!??

When i try your unity package in Emulator it is showing error " Could not copy the file ____SharingClient.dll" Because it was not found" Can you help me regarding this..??

**Comment by lolo8304** [comment]
you have to add it from Hololens "HoloToolkit-Unity" from github https://github.com/Microsoft/HoloToolkit-Unity / download zip and unpack it


- go to Unity project tree
- Assets/HoloToolkit/Sharing/Plugins/WSA
- create folder x86
- "import new asset ...." on this folder
- go to unpacked folder HoloToolkit-Unity\External\HoloToolkit\Sharing\Tools\SessionManager\x86
- select "sharingclient.dll"
- "import"

- select "sharingclient.dll"
- choose "WSA player", SDK = UWP, CPU=X86
- click "apply"

build again from unity and build it

**Comment by einstyle** [comment]
I have the same error of eswarborra when I run the build with Visual Studio on Hololens. I´ve tried your steps but still the same error...

**Comment by einstyle** [comment]
OK, it seems I get it working replacing the entire folder Holotoolkit with the latest one

**Comment by ActiveNick** [comment]
My apologies. I have not touched this repo in months and it was built with an older version of Unity, and using the older toolkit too. My goal it to update it this summer to the latest of everything, and I will be refactoring a lot of it to adjust to the latest techniques in the HoloToolkit.

**Comment by einstyle** [comment]
No problem.
Anyway, the application is amazing!

**Comment by ActiveNick** [comment]
I removed all the sharing components that were in the project since they were not needed anyways. The project has been updated to Unity 5.6.2f1 and now uses the Direct Line 3.0 API. I am currently in the process of updating to the latest version of the HoloToolkit. Stay tuned.
