### ISSUE TITLE
No TTS Sound in HL2

### ISSUE THREAD

**Issue by MrFabouMR** [ActiveNick/HoloBot#20]
Hey!

I pulled your project, imported it into Unity 2018.4.14f1 and tried it out with a HL2.

I get the playback sound from the tts in the unity editor but not in the HL2.

ping and hover sounds works.

It says "connection failure"

hope you can help me.

greetings.

**Comment by ActiveNick** [comment]
Which version of the speech SDK are you using? It's possible that the latest version has issues in this older version of Unity. I'm not actively developing this right now but I have plans to revisit it, upgrade everything, and add features when I find the free cycles that the pandemic took away.

**Comment by MrFabouMR** [comment]
I can close it already. You were absolutely right! I updated the version to the latest speech sdk and it works like a dream.
Thank you very much :-)
