### ISSUE TITLE
HoloBot not connecting with my bot

### ISSUE THREAD

**Issue by prlosana** [ActiveNick/HoloBot#8]
I downloaded the code, changed the default key to my bot's key as per your instructions, but it can't connect. At the Bot console (dev.botframework.com) I get the following error: 

"There was an error sending this message to your bot: HTTP status code Forbidden. "

My impression is that is looking for the name of the project besides the key. Any idea why is not working? Thanks!

P.s. Fantastic demo!

**Comment by ToPeter** [comment]
Same issue!

**Comment by ActiveNick** [comment]
Closing this out for now. Please try again with the new code in the Dev-2018.4-MRTKv2 branch since many changes have been made to the DirectLine bot integration code.
