### ISSUE TITLE
HoloToolkit dir causes build problems

### ISSUE THREAD

**Issue by deadlyfingers** [ActiveNick/HoloBot#9]
Currently the HoloToolkit dir causes a number of UWP build issues in Unity.
The solution is to delete this directory and reimport the [MR Toolkit](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases) back into Unity again.

**Comment by ActiveNick** [comment]
Thanks David, I'll have to look into this. It's possible that my .gitignore is messed up and omits key files. I will update the README to encourage others to use this workaround.

**Comment by ActiveNick** [comment]
Closing this out for now since the new version currently in the Dev-2018.4-MRTKv2 branch has been completely rebuild and no longer uses the original version of HTK.
